<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$CI =& get_instance();

$DataTableConfig =  array(
        'ajaxdatasource'  =>site_url('api/access/datalist'),
        'tableid'         =>'access_List',
        'dbtable'         =>'',
        'dbtableprimary'  =>'',
        'title'           =>'',
        'defaultorder'    =>array([2,'asc']),
        'dataexport'      =>true,
        'tablecondensed'  =>false,
        'bactionscolumn'  =>array(
                              "enable"        =>true,
                              "add"           =>false,
                              "addmethod"     =>'', // js function call
                              "view"          =>true,
                              "viewmethod"    =>'', // js function call
                              "edit"          =>false,
                              "editmethod"    =>'', // js function call
                              "delete"        =>false,
                              "deletemethod"  =>'', // js function call
                              "checkbox"      =>false,
                              "indexnumber"   =>true,
                          ),
        'column'          =>array(
                                                            
                                array(
                                  'fieldid'            => 'DataCount',
                                  'fieldlabel'         => 'LOG ID',
                                  'fieldtype'          => 'text',
                                  'base64_encrypted'   => false,
                                  'searchable'         => false,
                                  'advancesearch'      => false,
                                  'orderable'          => false,
                                  'width'              => '5',
                                  'className'          => 'font-size-10 text-uppercase align-middle',
                                  'visible'            => false,
                                  'exportable'         => false,
                                  'inputdisplay'       => 'input',
                                  'inputcustomattr'    => '',
                                  'inputcustomclass'   => 'text-uppercase',
                                  'referenceid'        => '',
                                  'referencefilter'    => '',
                                  'referenceorder'     => '',
                                  'parentfieldid'      => '',
                                  'childfieldid'       => '',
                                  'childfieldfilter'   => '',
                                ),

                                array(
                                  'fieldid'            => 'FacilityName',
                                  'fieldlabel'         => 'FACILITY NAME',
                                  'fieldtype'          => 'text',
                                  'base64_encrypted'   => false,
                                  'searchable'         => true,
                                  'advancesearch'      => true,
                                  'orderable'          => true,
                                  'width'              => '250px',
                                  'className'          => 'font-size-10 text-uppercase align-middle  text-left',
                                  'visible'            => true,
                                  'exportable'         => true,
                                  'inputdisplay'       => 'text',
                                  'inputcustomattr'    => '',
                                  'inputcustomclass'   => 'text-uppercase',
                                  'referenceid'        => '',
                                  'referencefilter'    => '',
                                  'referenceorder'     => '',
                                  'parentfieldid'      => '',
                                  'childfieldid'       => '',
                                  'childfieldfilter'   => '',
                                ),
                                array(
                                  'fieldid'            => 'FacilityCode',
                                  'fieldlabel'         => 'FACILITY CODE',
                                  'fieldtype'          => 'text',
                                  'base64_encrypted'   => false,
                                  'searchable'         => true,
                                  'advancesearch'      => true,
                                  'orderable'          => true,
                                  'width'              => '40px',
                                  'className'          => 'font-size-10 text-uppercase align-middle  text-center',
                                  'visible'            => true,
                                  'exportable'         => true,
                                  'inputdisplay'       => 'text',
                                  'inputcustomattr'    => '',
                                  'inputcustomclass'   => 'text-uppercase',
                                  'referenceid'        => '',
                                  'referencefilter'    => '',
                                  'referenceorder'     => '',
                                  'parentfieldid'      => '',
                                  'childfieldid'       => '',
                                  'childfieldfilter'   => '',
                                ),
                                array(
                                  'fieldid'            => 'organizationid',
                                  'fieldlabel'         => 'ORGANIZATION RESOURCE ID',
                                  'fieldtype'          => 'text',
                                  'base64_encrypted'   => false,
                                  'searchable'         => true,
                                  'advancesearch'      => true,
                                  'orderable'          => true,
                                  'width'              => '40px',
                                  'className'          => 'font-size-10 text-uppercase align-middle  text-center',
                                  'visible'            => true,
                                  'exportable'         => true,
                                  'inputdisplay'       => 'text',
                                  'inputcustomattr'    => '',
                                  'inputcustomclass'   => 'text-uppercase',
                                  'referenceid'        => '',
                                  'referencefilter'    => '',
                                  'referenceorder'     => '',
                                  'parentfieldid'      => '',
                                  'childfieldid'       => '',
                                  'childfieldfilter'   => '',
                                ),

                                // array(
                                //   'fieldid'            => 'emailaddress',
                                //   'fieldlabel'         => 'EMAIL ADDRESS',
                                //   'fieldtype'          => 'text',
                                //   'base64_encrypted'   => false,
                                //   'searchable'         => true,
                                //   'advancesearch'      => true,
                                //   'orderable'          => true,
                                //   'width'              => '40px',
                                //   'className'          => 'font-size-10 align-middle  text-center',
                                //   'visible'            => false,
                                //   'exportable'         => false,
                                //   'inputdisplay'       => 'text',
                                //   'inputcustomattr'    => '',
                                //   'inputcustomclass'   => '',
                                //   'referenceid'        => '',
                                //   'referencefilter'    => '',
                                //   'referenceorder'     => '',
                                //   'parentfieldid'      => '',
                                //   'childfieldid'       => '',
                                //   'childfieldfilter'   => '',
                                // ),

                                // array(
                                //   'fieldid'            => 'api_key',
                                //   'fieldlabel'         => 'API KEY',
                                //   'fieldtype'          => 'text',
                                //   'base64_encrypted'   => false,
                                //   'searchable'         => true,
                                //   'advancesearch'      => true,
                                //   'orderable'          => true,
                                //   'width'              => '150px',
                                //   'className'          => 'font-size-10 align-middle  text-center',
                                //   'visible'            => false,
                                //   'exportable'         => false,
                                //   'inputdisplay'       => 'text',
                                //   'inputcustomattr'    => '',
                                //   'inputcustomclass'   => 'text-uppercase',
                                //   'referenceid'        => '',
                                //   'referencefilter'    => '',
                                //   'referenceorder'     => '',
                                //   'parentfieldid'      => '',
                                //   'childfieldid'       => '',
                                //   'childfieldfilter'   => '',
                                // ),

                                // array(
                                //   'fieldid'            => 'User_E_Key',
                                //   'fieldlabel'         => 'ENCRYPTION KEY',
                                //   'fieldtype'          => 'text',
                                //   'base64_encrypted'   => false,
                                //   'searchable'         => true,
                                //   'advancesearch'      => true,
                                //   'orderable'          => true,
                                //   'width'              => '150px',
                                //   'className'          => 'font-size-10 align-middle  text-center',
                                //   'visible'            => false,
                                //   'exportable'         => false,
                                //   'inputdisplay'       => 'text',
                                //   'inputcustomattr'    => '',
                                //   'inputcustomclass'   => 'text-uppercase',
                                //   'referenceid'        => '',
                                //   'referencefilter'    => '',
                                //   'referenceorder'     => '',
                                //   'parentfieldid'      => '',
                                //   'childfieldid'       => '',
                                //   'childfieldfilter'   => '',
                                // ),
                                // array(
                                //   'fieldid'            => 'user_id',
                                //   'fieldlabel'         => 'USER ID',
                                //   'fieldtype'          => 'text',
                                //   'base64_encrypted'   => false,
                                //   'searchable'         => false,
                                //   'advancesearch'      => false,
                                //   'orderable'          => false,
                                //   'width'              => '150px',
                                //   'className'          => 'font-size-10 text-uppercase align-middle  text-center',
                                //   'visible'            => false,
                                //   'exportable'         => false,
                                //   'inputdisplay'       => 'text',
                                //   'inputcustomattr'    => '',
                                //   'inputcustomclass'   => 'text-uppercase',
                                //   'referenceid'        => '',
                                //   'referencefilter'    => '',
                                //   'referenceorder'     => '',
                                //   'parentfieldid'      => '',
                                //   'childfieldid'       => '',
                                //   'childfieldfilter'   => '',
                                // ),

                              ),
        'autoscrollx'       =>false,
        'scrollx'           =>false,
        'scrollpagination'  =>false,
        'actiobbuttons'     =>@$actionButtons, // html content
        'fixedcolumns'      =>array("leftColumns"=>0,"rightColumns"=>0), 
        'callbackjsfunction'=>'',
        'bordercolor'       =>'headercolor',
        'pushparameter'     =>['Mode' => 1]
      );


?>

<div>
<?php echo $CI->datatables->ShowDataTable($DataTableConfig); ?>
</div>
<script id="removethis" nonce="<?php echo $CI->nonceV; ?>" type="text/javascript">
$(document).ready(function(){ 
  
});
</script>