<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$CI =& get_instance();

$DataTableConfig =  array(
    'ajaxdatasource'  =>site_url('download/download_List'),
    'tableid'         =>'DownloadList',
    'dbtable'         =>'',
    'dbtableprimary'  =>'',
    'title'           =>'',
    'panelclass'      =>'bg-transparent',
    'headershow'      =>true,
    'headerclass'     =>'siteheaderbg align-middle text-white',
    'footershow'      =>false,
    'footerclass'     =>'sitepanelbg',
    'defaultorder'    =>array(array(8,'desc')),
    'dataexport'      =>false,
    'tablecondensed'  =>false,
    'bactionscolumn'  =>array(
                          "enable"        =>true,
                          "add"           =>false,
                          "addmethod"     =>'', // js function call
                          "view"          =>true,
                          "viewmethod"    =>'', // js function call
                          "edit"          =>false,
                          "editmethod"    =>'', // js function call
                          "delete"        =>false,
                          "deletemethod"  =>'', // js function call
                          "checkbox"      =>false,
                          "indexnumber"   =>false,
                      ),
    'column'          =>array(
                            
                            array(
                              'fieldid'            => 'DataID',
                              'fieldlabel'         => '',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '5%',
                              'className'          => '',
                              'visible'            => false,
                              'exportable'         => false,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'DownloadFile_Title',
                              'fieldlabel'         => 'FILE NAME / TITLE',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => true,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '45%',
                              'className'          => 'text-left text-uppercase font-size-18',
                              'visible'            => true,
                              'exportable'         => true,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'DownloadFile_FileID',
                              'fieldlabel'         => 'FILE ID',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '45%',
                              'className'          => '',
                              'visible'            => false,
                              'exportable'         => false,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'File_FileName',
                              'fieldlabel'         => 'Type',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '10%',
                              'className'          => '',
                              'visible'            => false,
                              'exportable'         => false,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'File_Description',
                              'fieldlabel'         => 'DESCRIPTION',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => true,
                              'width'              => '30%',
                              'className'          => '',
                              'visible'            => false,
                              'exportable'         => true,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'File_FileType',
                              'fieldlabel'         => 'TYPE',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '10%',
                              'className'          => 'text-uppercase text-center',
                              'visible'            => true,
                              'exportable'         => true,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'File_FileSize',
                              'fieldlabel'         => 'SIZE',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '10%',
                              'className'          => ' text-center',
                              'visible'            => true,
                              'exportable'         => true,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),

                            array(
                              'fieldid'            => 'DownloadCounter',
                              'fieldlabel'         => 'DOWNLOAD COUNT',
                              'fieldtype'          => 'text',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => false,
                              'width'              => '25%',
                              'className'          => 'text-center',
                              'visible'            => true,
                              'exportable'         => true,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),
                            // array(
                            //   'fieldid'            => 'FileExternalURL',
                            //   'fieldlabel'         => 'External File',
                            //   'fieldtype'          => 'text',
                            //   'base64_encrypted'   => false,
                            //   'searchable'         => false,
                            //   'advancesearch'      => false,
                            //   'orderable'          => true,
                            //   'width'              => '',
                            //   'className'          => '',
                            //   'visible'            => false,
                            //   'exportable'         => false,
                            //   'inputdisplay'       => 'text',
                            //   'inputcustomattr'    => '',
                            //   'inputcustomclass'   => '',
                            //   'referenceid'        => '',
                            //   'referencefilter'    => '', 
                            //   'referenceorder'     => '', 
                            //   'parentfieldid'      => '',
                            //   'childfieldid'       => '',
                            //   'childfieldfilter'   => '',
                            //   'parentfieldid'      => '',
                            // ),
                            array(
                              'fieldid'            => 'PublishedS_DateTime',
                              'fieldlabel'         => 'Published Date/Time',
                              'fieldtype'          => 'datetime',
                              'base64_encrypted'   => false,
                              'searchable'         => false,
                              'advancesearch'      => false,
                              'orderable'          => true,
                              'width'              => '20%',
                              'className'          => '',
                              'visible'            => false,
                              'exportable'         => true,
                              'inputdisplay'       => 'text',
                              'inputcustomattr'    => '',
                              'inputcustomclass'   => '',
                              'referenceid'        => '',
                              'referencefilter'    => '', 
                              'referenceorder'     => '', 
                              'parentfieldid'      => '',
                              'childfieldid'       => '',
                              'childfieldfilter'   => '',
                              'parentfieldid'      => '',
                            ),
                          ),
    'scrollx'           =>false,
    'scrollpagination'  =>false,
    'actiobbuttons'     =>'', // html content
    'fixedcolumns'      =>array("leftColumns"=>0,"rightColumns"=>0), 
    'callbackjsfunction'=>'',
    'bordercolor'       =>'', 
    'lengthChange'      =>false,

  );
?>

<div class="">  
    <?php echo $CI->datatables->ShowDataTable($DataTableConfig); ?>
</div>

<script id="removethis" nonce="<?php echo $CI->nonceV; ?>" type="text/javascript">
$(document).ready(function(){


});  
</script>
